### ISSUE TITLE
From: Redpill (Unix?)

### ISSUE THREAD

**Issue by KiddieD** [Hopson97/Community-Game#85]
./Community-Game
Unable to read res/settings/Controls.json
terminate called after throwing an instance of 'nlohmann::detail::parse_error'
  what():  [json.exception.parse_error.101] parse error at 1: parse error - unexpected end of input
Aborted (core dumped)

**Comment by 0Zix0** [comment]
This was happening to me, the issue was that the 'res' file was not in the correct place.

**Comment by brobotato** [comment]
I had this error too - I moved the exe from cmake-build-debug to the root folder and it worked.

**Comment by BeefEX** [comment]
This should be closed now, also there should be catch for that error.
